module: models.googlenet
model: GoogLeNet
state_dict_path: "../../../models/state_dicts/googlenet.pt"
preprocessing:
  {
    "mean": [0.4914, 0.4822, 0.4465],
    "std": [0.2023, 0.1994, 0.2010],
    "axis": -3,
  }
device: "cpu"
